nishgo/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'novago'

urlpatterns = [
    path('', views.redirect_view),
    path('novago/', include('novago.urls')),
    path('admin/', admin.site.urls),
    
]

novago/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = 'novago'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('create-account/', create_account, name='create_account'),
    path('edit-profile/', edit_profile, name='edit_profile'),
    path('driver/', reg_driver, name='reg_driver'),
    path('search/', search, name='search'),
    path('callback/', callback, name='callback'),
    path('new-trip/', new_trip, name='new-trip'),
    path('new-request/', new_request, name='new-request'),
    path('your-trips/modify_trip/<int:trip_id>',
         modify_trip, name='modify_trip'),
    path('your-trips/cancel_trip/<int:trip_id>',
         cancel_trip, name='cancel_trip'),
    path('your-trips/modify_trip/kick_passenger/<int:trip_id>/<int:passenger_id>',
         kick_passenger, name='kick_passenger'),
    path('your-trips/kick-yourself/<int:trip_id>',
         kick_yourself, name='kick-yourself'),
    path('your-trips/', yourTrips, name='your-trips'),
    path('your-trips/<int:trip_id>-booked', book, name='book'),
    path('your-trips/<int:trip_id>-accepted', take, name='take'),
    path('your-trips/booking-failed/<int:message>', yourTrips, name='failed'),
    path('<destination_address>/get_marker_data/',
         get_marker_data, name='get_marker_data'),
    path('profile/', profile, name='profile'),
    path('profile/<int:driver>', user_profile, name='user-profile'),
    path('rate/<int:trip_id>', rate, name='rate'),
    path('config/', stripe_config, name='config'),  # new
    path('create-checkout-session/', create_checkout_session,
         name='create_checkout_session'),  # new
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

novago/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import *
import datetime

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ("profile_picture","first_name","last_name","profile_description")
        widgets = {'profile_picture' : forms.FileInput(attrs={"id": "file-input"})}


class SearchForm(forms.Form):
    where = forms.CharField(label='Where', max_length=100, required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Where', 'id': 'autocomplete', }))
    depart_date = forms.DateField(label='When', widget=forms.DateInput(
        attrs={'type': 'date'}), required=False)


class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ('destination_address', 'starting_address',
                  'depart_date', 'depart_time', 'stops', 'passengers_amount', 'price')
        cur_datetime = datetime.datetime.now()
        cur_date = cur_datetime.date().strftime("%Y-%m-%d")
        widgets = {
            'starting_address': forms.TextInput(attrs={'class': 'textbox w-input',
                                                       'label': 'destination-address',
                                                       'placeholder': 'Starting Address',
                                                       'id': 'autocomplete1',
                                                       'name': 'destination_address', }),

            'destination_address': forms.TextInput(attrs={'class': 'textbox w-input',
                                                          'label': 'destination-address',
                                                          'placeholder': 'Destination Address',
                                                          'id': 'autocomplete',
                                                          'name': 'destination_address', }),
            'depart_date': forms.DateInput(attrs={'type': 'date', 'class': 'textbox w-input', 'min':cur_date}),
            'depart_time': forms.TimeInput(attrs={'type': 'time'}),
            'price': forms.NumberInput(attrs={'type': 'number', 'title':'Price per passenger', 'min':'0', 'max':'100'}),
            'passengers_amount': forms.NumberInput(attrs={'type': 'number', 'title':'Price per passenger', 'min':'0', 'max':'8'})
        }


class LoginForm(forms.Form):
    user = forms.EmailField(label='Email', required=True)
    password = forms.SlugField(label='Password', required=True, widget=forms.PasswordInput(
        attrs={'class': 'textbox w-input'}, render_value=False))


class FilterForm(forms.Form):
    location = forms.BooleanField(
        label="Filter by location", widget=forms.RadioSelect(choices=[('Exact', True)]))
    date = forms.BooleanField(label="Filter by date", widget=forms.RadioSelect(
        choices=[('Exact', False), ('Range', True)]))
    range_start = forms.DateField(label="Start", widget=forms.DateInput(
        attrs={'type': 'date', 'class': 'textbox w-input'}))
    range_end = forms.DateField(label="End", widget=forms.DateInput(
        attrs={'type': 'date', 'class': 'textbox w-input'}))
    if date:
        range_start.required = True
        range_end.required = True
        # self.fields['range_end'].validators = [validateDates]


class BookingForm(forms.Form):
    class Meta:
        model = Booking
        fields = ("__all__")


class RatingForm(forms.Form):
    class Meta:
        model = Rating
        fields = ("rating")

novago/views.py
import json
from django.shortcuts import render, redirect
from django.core.files.storage import default_storage
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.conf import settings
import datetime
import pytz
import requests
from django.views.decorators.csrf import csrf_protect
import os
from django.core import serializers
# Create your views here.
from django.utils import timezone
from .models import *
from .forms import *
from authlib.integrations.django_client import OAuth
from urllib.parse import quote_plus, urlencode
from authlib.integrations.django_oauth2 import ResourceProtector
from . import validator
from django.urls import reverse
import stripe

# registers the remote application (novago)
# needs your variables set in env (i sent them, can again)
oauth = OAuth()

oauth.register(
    "novago",
    client_id=settings.AUTH0_CLIENT_ID,
    client_secret=settings.AUTH0_CLIENT_SECRET,
    # this is the scope (so we can like deny access for driver/passenger or whatever right)
    # not sure though if should like not add any here then, only in the auth stuff?
    # should solve
    client_kwargs={
        "scope": "openid profile email",
    },
    # this is like the auth redirect url for some reason
    server_metadata_url=f"https://{settings.AUTH0_DOMAIN}/.well-known/openid-configuration",
)

DRIVER_PICS = ['driver1.jpg', 'driver2.jpg', 'driver3.jpg', 'driver4.jpg', 'driver5.jpg']


# should probably add csrf protect to these new functions?
# but not sure how that would work bc no forms really
# and they go to pages we don't have the html for really,,,

# after login redirects to home page


def callback(request):
    token = oauth.novago.authorize_access_token(request)
    request.session["user"] = token
    # makes a new account and passes id to create account or finds attached account
    if Account.objects.filter(sub=request.session.get("user")["userinfo"]["sub"]).count() != 0:
        request.session["user"]["user_id"] = Account.objects.filter(
            sub=request.session.get("user")["userinfo"]["sub"])[0].account_id
    else:
        a = Account(sub=request.session.get("user")["userinfo"]["sub"])
        a.save()
        request.session["user"]["user_id"] = a.account_id
        return redirect(request.build_absolute_uri(reverse('novago:create_account')))
    return redirect(request.build_absolute_uri(reverse('novago:index')))

# sends to auth0 login (callback)s


def login(request):
    return oauth.novago.authorize_redirect(
        request, request.build_absolute_uri(reverse("novago:callback"))
    )

# (hopefully logs out of all browsers ? will need to test)


def logout(request):
    request.session.clear()
    # clears session

    return redirect(
        f"https://{settings.AUTH0_DOMAIN}/v2/logout?"
        + urlencode(
            {
                "returnTo": request.build_absolute_uri(reverse("novago:index")),
                "client_id": settings.AUTH0_CLIENT_ID,
            },
            quote_via=quote_plus,
        ),
    )

# function to check if user is logged in
def check_scope(request):
    try:
        user_id = request.session.get("user").get("user_id")
    except:
        return False
    return user_id


# index view
# default shows all rides and no requests
@csrf_protect
def index(request):
    # call check scope
    # if not logged in, send to login, otherwise continue
    user_id = check_scope(request)
    if not user_id:
        user_id = 22
    # only display upcoming trips with available seats
    user = Account.objects.get(pk=user_id)
    trips = [i if i.booked.count() <= i.passengers_amount and i.depart_date > datetime.date.today() and i.driver != Account.objects.get(pk=22) else '' for i in Trip.objects.all()]
    while trips.count('') != 0:
        trips.remove('')

    form = SearchForm(request.POST)

    data = serializers.serialize('python', trips)

    for d in data[:]:  # Make a copy of the original list to iterate over
        field = d['fields']
        if field['destination_address'] == '' or field['starting_address'] == '':
            data.remove(d)
        else:
            del field['date_published']
            del field['date_modified']
            del field['depart_time']
            del field['depart_date']

    data_list = [d['fields'] for d in data]

    context = {"user_id": user_id,
                'user': user,
               'triplist': trips,
               'form': form,
               'filters': FilterForm(request.POST),
               'json_trip_list': json.dumps(data_list),
               "session": request.session.get("user"),
               'google_api_key': settings.API_KEY,
               "pretty": json.dumps(request.session.get("user"), indent=4), }
    # only drivers see requests
    if Driver.objects.filter(account=user).count() != 0:
        trip_requests = [[i, Booking.objects.filter(trip=i)[0].account] if i.driver == Account.objects.get(pk=22) and Booking.objects.filter(trip=i).count() != 0 else '' for i in Trip.objects.all()]
        while trip_requests.count('') != 0:
            trip_requests.remove('')
        context['requestlist'] = trip_requests
    return render(request, 'main.html', context)


@ csrf_protect
def search(request):
    # call check scope
    # if not logged in, send to login, otherwise continue
    user_id = check_scope(request)
    if not user_id:
        return redirect(request.build_absolute_uri(reverse('novago:login')))
    # currently filters by trip destination using filterLocation
    # request will eventually contain filter arguments which will dictate the search function
    destination_address = request.POST["where"]
    filtered_trips = Trip.objects.filter(
        destination_address=destination_address)
    
    # only display upcoming trips with available seats
    user = Account.objects.get(pk=user_id)
    trips = [i if i.booked.count() <= i.passengers_amount and i.depart_date > datetime.date.today() and i.driver != Account.objects.get(pk=22) else '' for i in filtered_trips]
    while trips.count('') != 0:
        trips.remove('')

    data = serializers.serialize('python', filtered_trips)
    for d in data[:]:  # Make a copy of the original list to iterate over
        field = d['fields']
        if field['destination_address'] == '' or field['starting_address'] == '':
            data.remove(d)
        else:
            del field['date_published']
            del field['date_modified']
            del field['depart_time']
            del field['depart_date']

    data_list = [d['fields'] for d in data]

    # k whatever were loading the page again
    context = {'user_id': user_id,
                'user': Account.objects.get(pk=user_id),
               'destination_address': destination_address,
               "session": request.session.get("user"),
               'triplist': filtered_trips,
               'json_trip_list': json.dumps(data_list),
               'form': SearchForm(request.POST),
               'google_api_key': settings.API_KEY}
    if Driver.objects.filter(account=user).count() != 0:
        trip_requests = [[i, Booking.objects.filter(trip=i)[0].account] if i.driver == Account.objects.get(pk=22) and Booking.objects.filter(trip=i).count() != 0 else '' for i in filtered_trips]
        while trip_requests.count('') != 0:
            trip_requests.remove('')
        context['requestlist'] = trip_requests
    return render(request, 'main.html', context)


def get_marker_data(request, destination_address):
    """AJAX call to get marker data"""
    if request.session.get("user"):
        user_id = request.session["user"]["user_id"]
    else:
        user_id = 1
    if request == 'GET':
        # get the search results from the database
        current_user = Account.objects.get(account_id=user_id)
        trip_list = Trip.objects.filter(
            destination_address=destination_address).exclude(driver=current_user)
        # return the results in a json format
        response_data = [{'address': trip.destination_address}
                         for trip in trip_list]
        return JsonResponse(response_data)


@ csrf_protect
def edit_profile(request):
    # call check scope
    # if not logged in, send to login, otherwise continue
    user_id = check_scope(request)
    if not user_id:
        return redirect(request.build_absolute_uri(reverse('novago:login')))
    # if there's input, set user info
    user = Account.objects.get(pk=user_id)
    if request.POST.get("first_name") and request.POST.get("first_name") != "":
        user.first_name = request.POST.get("first_name")
    if request.POST.get("last_name") and request.POST.get("last_name") != "":
        user.last_name = request.POST.get("last_name")
    if request.POST.get("profile_description") and request.POST.get("profile_description") != "":
        user.profile_description = request.POST.get("profile_description")
    if request.POST.get("address") and request.POST.get("address") != "":
        user.address = request.POST.get("address")
    # can't write to heroku server in production for free so just choose a pic from our repo
    if request.FILES.get("profile_picture") and request.FILES.get("profile_picture") != "":
        user.profile_picture = request.FILES.get("profile_picture")
        hash_pic = user.profile_picture.__hash__()
        user.profile_picture = 'profile_pictures/' + DRIVER_PICS[hash_pic % 5]
    user.save()
    return redirect(request.build_absolute_uri(reverse('novago:profile')))


@ csrf_protect
def create_account(request):
    # call check scope
    # if not logged in, send to login, otherwise continue
    user_id = check_scope(request)
    if not user_id:
        return redirect(request.build_absolute_uri(reverse('novago:login')))
    else:
        user=Account.objects.get(pk=user_id)
        pic = user.profile_picture
        context = {"user_id": user_id, "user": Account.objects.get(pk=user_id), 'pic': pic}

novago/templates/fail_to_book.html
{% extends "template.html" %}
{% load static %}
{% load widget_tweaks%}

{% block all %}
<a href="{% url 'novago:index' %}">
    <div class="exit-button"><i class='far fa-window-close' style='font-size:36px'></i></div>
</a>
<div>
    <p>{{ message }}</p>
</div>
{%endblock all%}

novago/templates/main.html
{% extends "template.html" %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<!-- container with ride and request tabs -->
<div class="col-5">
    <div class="tab-format">
        <input class="radio" id="one" name="group" type="radio" checked>
        <input class="radio" id="two" name="group" type="radio">
        <div class="tabs tab-header">
        <label class="tab" id="one-tab" for="one">rides</label>
        <label class="tab" id="two-tab" for="two">requests</label>
        </div>
        {% comment %} 
        ? to do here: on click of trip that show that trip on the 
        ? map with the route pickup and drop off 
        {% endcomment %}

        <!-- ride list -->
        <div class="panels tab-container container">
            <div class="panel" id="one-panel">
                <div class="list">
                    <!-- ride list with either a list of trip cards or one card saying no trips -->
                    {% if triplist.type != QuerySet %}
                    <p>
                        Sorry, no trips were found.
                    </p>
                    
                    {% else %}
                    {% for trip in triplist %}
                    <div class="list-item">
                            <img src="{% static trip.driver.profile_picture.name %}" class="list-icon"/>
                            <ul>
                                <li>
                                    Driver: {{ trip.driver.first_name }}
                                </li>
                                <li>
                                    Where: {{ trip.destination_address }}
                                </li>
                                <li>
                                    When: {{ trip.depart_date }}
                                </li>
                                <li>
                                    Rating: {{ trip.driver.rating }}
                                </li>
                            </ul>
                            <button class="button" onclick="showModal({{trip.trip_id}})" >View</button>
                            <div id="{{trip.trip_id}}" class="modal">
                            <div class="modal-content">
                                   <span class="close" id="close{{trip.trip_id}}">&times;</span></button>
                                <form action="{% url 'novago:book' trip.trip_id %}" method="post">
                                    {% csrf_token %}
                                    <img src="{% static trip.driver.profile_picture.name %}" class="list-icon"/>
                                    <ul>
                                        <li>
                                            Driver: <a href="{% url 'novago:user-profile' trip.driver.account_id %}">{{ trip.driver.first_name }} {{ trip.driver.last_name }}</a>
                                        </li>
                                        <li>
                                            Where: {{ trip.starting_address }} to {{ trip.destination_address }}
                                        </li>
                                        <li>
                                            When: {{ trip.depart_date }} at {{ trip.depart_time }}
                                        </li>
                                        <li>
                                            Rating: {{ trip.driver.rating }}
                                        </li>
                                        <li>
                                            Passengers: {{ trip.passengers_amount }}
                                        </li>
                                        <li>
                                            Price: ${{ trip.price }}
                                        </li>
                                    </ul>
                                    <button type="submit" class="button field1" id="my_button">Book</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
            <!-- request list -->
            <div class="panel" id="two-panel">
                <div class="list">
                    <!-- ride list with either a list of trip cards or one card saying no trips -->
                    {% for request in requestlist %}
                    <div class="list-item">
                            <img src="{% static request.1.profile_picture.name %}" class="list-icon"/>
                            <ul>
                                <li>
                                    Requester: {{ request.1.first_name }}
                                </li>
                                <li>
                                    Where: {{ request.0.destination_address }}
                                </li>
                                <li>
                                    When: {{ request.0.depart_date }}
                                </li>
                                <li>
                                    Rating: {{ request.1.rating }}
                                </li>
                            </ul>
                            <button class="button" onclick="showModal({{ request.0.trip_id }})" >View</button>
                            <div id="{{ request.0.trip_id }}" class="modal">
                                <div class="modal-content">
                                    <span class="close" id="close{{request.0.trip_id}}">&times;</span></button>
                                <form action="{% url 'novago:take' request.0.trip_id %}" method="post">
                                    {% csrf_token %}
                                    <img src="{% static request.1.profile_picture.name %}" class="list-icon"/>
                                    <ul>
                                        <li>
                                            Requester: <a href="{% url 'novago:user-profile' request.1.account_id %}">{{ request.1.first_name }} {{ request.1.last_name }}</a>
                                        </li>
                                        <li>
                                            Where: {{ request.0.starting_address }} to {{ request.0.destination_address }}
                                        </li>
                                        <li>
                                            When: {{ request.0.depart_date }} at {{ request.0.depart_time }}
                                        </li>
                                        <li>
                                            Rating: {{ request.1.rating }}
                                        </li>
                                        <li>
                                            Passengers: {{ request.0.passengers_amount }}
                                        </li>
                                        <li>
                                            Price: ${{ request.0.price }}
                                        </li>
                                    </ul>
                                    <button type="submit" class="button field1" id="my_button">Accept</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            </div>
        </div>
    </div>
</div>

<!-- map with search form in header -->
<div class="col-5-5">
    <div class="container">
        <div class="container-header header">
            <form class="header-form" action="{% url 'novago:search' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <input id="ride-search-button" type="submit" value="search" class="button" data-user-id="{{ user_id }}" />
            </form>
        </div>
        
        <div class="map" id="mapholder">
        {% comment %} for every trip given in triplist, create and add a marker to the map  {% endcomment %}
            <script type="text/javascript">
                var json_trip_list = {{ json_trip_list|safe }};
            
                var addresses = [];
                for (var i = 0; i < json_trip_list.length; i++) {
                    addresses.push(json_trip_list[i].starting_address);
                    addresses.push(json_trip_list[i].destination_address);
                }
                console.log(addresses);
                console.log(json_trip_list);
            </script>
            <script defer src={% static 'js/generate_map.js' %}> </script>
        </div>
    </div>
</div>

{% endblock content%}

novago/templates/navbar.html
<nav id="mySidenav" role="navigation" class="w-nav-menu col-1 navbar">
  <!-- test link to profile, user 1 creates an account, will eventually take logged in user's id -->
  <ul>
    <li>
      <a href="{% url 'novago:profile'%}" class="w-nav-link" data-title="Profile">
        <i class="icon fa-solid fa-user"></i>
      </a>
      <p class="subtitle">profile</p>
    </li>
    <li>
      <a href="{% url 'novago:new-trip' %}" class="w-nav-link" data-title="Post a Trip">
        <i class="icon fas fa-clipboard"></i>
      </a>
      <p class="subtitle">post</p>
    </li>
    <li>
      <a href="{% url 'novago:your-trips' %}" class="w-nav-link" data-title="Your Trips">   
        <i class="icon fa-solid fa-car-side"></i>
      </a>
      <p class="subtitle">trips</p>
    </li>
  </ul>
</nav>

novago/templates/rate.html
{% extends "template.html" %}
{% load static %}
{% load widget_tweaks%}

{% block all %}
<a href="{% url 'novago:profile' %}">
    <div class="exit-button"><i class='far fa-window-close' style='font-size:36px'></i></div>
</a>
<div>
    <form action="{% url 'novago:rate' trip %}" method="post">
        {% csrf_token %}
        <label for="rating">Rating</label>
        <input name="rating" type="float"/>
        <label for="description">Review</label>
        <input name="description" type="text"/>
        <input type="submit" value="rate"/>
    </form>
    {% if message %}
    <div class="modal" id="failed_booking" style="display:block">
        <div class="modal-content">
            <button onclick="document.getElementById('failed_booking').style.display='none'"><span class="close">&times;</span></button>
            <div>
                <p style="color:black;">{{ message }}</p>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{%endblock all%}

novago/templates/success_booking.html
{% extends "template.html" %}
{% load static %}
{% load widget_tweaks%}

{% block all %}
<a href="{% url 'novago:index' %}">
    <div class="exit-button"><i class='far fa-window-close' style='font-size:36px'></i></div>
</a>
<div>
    <p>You booked a trip! Send {{ driver }} ${{ price }}, please.</p>
    <a href="{% url 'novago:create_checkout_session' %}">Pay</button>
</div>
{%endblock all%}

novago/templates/your-trips.html
{% extends "template.html" %}
{% load static %}

{% block content %}

{% if message %}
<div class="modal" id="failed_booking" style="display:block">
    <div class="modal-content">
        <button onclick="document.getElementById('failed_booking').style.display='none'"><span class="close">&times;</span></button>
        <div>
            <p style="color:black;">{{ message }}</p>
        </div>
    </div>
</div>
{% endif %}

<div class="col-5">
        <!-- All past trips that you are a passenger OR a driver  -->
    <div class="tab-format">
        <input class="radio" id="one" name="group" type="radio" checked>
        <input class="radio" id="two" name="group" type="radio">
        <div class="tabs tab-header">
            <label class="tab" id="one-tab" for="one">upcoming</label>
            <label class="tab" id="two-tab" for="two">completed</label>
        </div>
        <div class="panels tab-container container">
            <div class="panel" id="one-panel">
                <div class="list">
                    {% for trip in upcoming_trips %}
                    <div class="list-item">
                        <img class="list-icon" src="{% static trip.driver.profile_picture.name %}" />
                        <ul>
                            <li>
                                Driver: {{ trip.driver.first_name }}
                            </li>
                            <li>
                                Where: {{ trip.destination_address }}
                            </li>
                            <li>
                                When: {{ trip.depart_date }}
                            </li>
                            <li>
                                Price: ${{ trip.price }}
                            </li>
                            <li>
                                Rating: {{ trip.driver.rating }}
                            </li>
                        </ul>
                        <a href="{%url 'novago:kick-yourself' trip.trip_id %}" class="button">Leave Trip</a>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="panel" id="two-panel">
                <div class="list">
                    {% for trip in past_trips %}
                        <div class="trip-list-item">
                            <img class="list-icon" src="{% static trip.driver.profile_picture.name %}" />
                            <ul>
                                <li>
                                    Driver: <a href="{% url 'novago:user-profile' trip.driver.account_id %}">{{ trip.driver.first_name }}</a>
                                </li>
                                <li>
                                    Where: {{ trip.destination_address }}
                                </li>
                                <li>
                                    When: {{ trip.depart_date }}
                                </li>
                                <li>
                                    Rating: {{ trip.driver.rating }}
                                </li>
                            </ul>
                            {% if trip not in rated_trips %}
                            <a href="{%url 'novago:rate' trip.trip_id %}" class="button">Rate Trip</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- this should display trip detail view -->
<div class="col-6">
    <div class="container">
        <div class="container-header header">Driver Trips</div>
        <div class="list">
        {% for trip in your_trips %}
        <div class="list-item">
            <img class="list-icon" src="{% static trip.driver.profile_picture.name %}" />
            <ul>
                <li>
                    Driver: {{ trip.driver.first_name }}
                </li>
                <li>
                    Where: {{ trip.destination_address }}
                </li>
                <li>
                    When: {{ trip.depart_date }}
                </li>
                <li>
                    Price: ${{ trip.price }}
                </li>
                <li>
                    <a href="{% url 'novago:modify_trip' trip.trip_id %}" class="button">Modify</a>
                    <a href="{% url 'novago:cancel_trip' trip.trip_id %}" class="button">Cancel</a>
                </li>
            </ul>
        </div>
        {% endfor %}
    </div>
    </div>
</div>
{%endblock content%}